config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :posts do
    resources :comments
  end

  resources :question_banks
  resources :question_categories

# Below are nested resources TODO fix them
  resources :question_sets

  resources :questions do
    resources :answers
  end

  resources :bounties
  get 'home/about'

  get 'home/contact'

  get 'home/index'

  root "home#index"

  devise_for :users, :path_prefix => 'my'
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  # scope "/account" do
  #   resources :users
  # end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  name        :text
#  correct     :boolean          default(FALSE)
#  question_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_answers_on_question_id  (question_id)
#

class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bounty.rb
# == Schema Information
#
# Table name: bounties
#
#  id         :integer          not null, primary key
#  amount     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Bounty < ApplicationRecord
  has_one :user
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  body       :text
#  post_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_comments_on_post_id  (post_id)
#

class Comment < ApplicationRecord
  belongs_to :post
  validates_presence_of :body
end

app/models/packet.rb
class Packet < ApplicationRecord
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, :dependent => :destroy
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id              :integer          not null, primary key
#  name            :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  explanation     :text
#  question_set_id :integer
#
# Indexes
#
#  index_questions_on_question_set_id  (question_set_id)
#

class Question < ApplicationRecord
  has_many :answers
  belongs_to :question_set
end

app/models/question_bank.rb
# == Schema Information
#
# Table name: question_banks
#
#  id         :integer          not null, primary key
#  name       :text
#  bounty     :integer          default(0)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class QuestionBank < ApplicationRecord
  has_many :question_sets, inverse_of: :question_bank
  accepts_nested_attributes_for :question_sets, reject_if: :all_blank, allow_destroy: true

end

app/models/question_category.rb
# == Schema Information
#
# Table name: question_categories
#
#  id          :integer          not null, primary key
#  name        :text
#  description :text
#  information :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class QuestionCategory < ApplicationRecord
  has_many :question_sets
end

app/models/question_set.rb
# == Schema Information
#
# Table name: question_sets
#
#  id                   :integer          not null, primary key
#  instruction          :text
#  guide                :text
#  question_category_id :integer
#  created_at           :datetime         not null
#  updated_at           :datetime         not null
#  name                 :text
#  question_bank_id     :integer
#
# Indexes
#
#  index_question_sets_on_question_bank_id      (question_bank_id)
#  index_question_sets_on_question_category_id  (question_category_id)
#

class QuestionSet < ApplicationRecord
  belongs_to :question_category
  belongs_to :question_bank
  has_many :questions
  accepts_nested_attributes_for :questions, allow_destroy: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string
#  age                    :integer
#  gender                 :integer          default("other")
#  phone                  :string           default("")
#  bounty_id              :integer
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  slug                   :string
#  avatar                 :string
#
# Indexes
#
#  index_users_on_bounty_id             (bounty_id)
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_slug                  (slug) UNIQUE
#

class User < ApplicationRecord
  extend FriendlyId
  friendly_id :email_and_id, use: :slugged
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  enum gender: [ :other,:male,:female ]
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  def should_generate_new_friendly_id?
    new_record? || slug.nil? || slug.blank? # you can add more condition here
  end

  def email_and_id
    puts "User id: "
    puts self.id
    "#{self.email.split(/@/).first}"
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/bounties_helper.rb
module BountiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/packets_helper.rb
module PacketsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/shared/_footer.html.erb
<div class="nav-navbar navbar-default text-center"  style="
  padding: 1rem;
  background-color: black;
  color: white;
  font-size: 16px;
  font-weight: bold;
  text-align: center;

">
  <footer class="footer">
    <div class="container">
      <p class="text-muted">Place sticky footer content here.</p>
    </div>
  </footer>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "SmartStudy", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to "QuestonCategory",  question_categories_path %>
        </li>

        <li>
          <%= link_to "QuestionBank",  question_banks_path %>
        </li>
        <li>
          <%= link_to "QuestonSET",   question_sets_path  %>
        </li>

        <li>
          <%= link_to "Questions",  questions_path %>
        </li>

        <li>
          <%= link_to "News", posts_path %>
        </li>

      </ul>
      <ul class="nav navbar-nav navbar-right">

        <% if user_signed_in? %>
        <li>
          <%= link_to user_path(current_user)  do %>
          <span class="glyphicon glyphicon-user"></span>
          My profile
          <% end %>

        </li>

        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <span class="glyphicon glyphicon-log-out"></span>
          Logout
          <% end %>

        </li>

      <% else %>
        <li>
          <%= link_to new_user_registration_path do %>
          <span class="glyphicon glyphicon-user"></span>
          Sign Up
          <% end %>

        </li>

        <li>
          <%= link_to new_user_session_path do %>
          <span class="glyphicon glyphicon-log-in"></span>
          Login
          <% end %>
          <% end %>
      </ul>
    </div>
  </div>
</nav>