config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :posts do
    resources :comments
  end

  resources :question_banks
  resources :question_categories

# Below are nested resources TODO fix them
  resources :question_sets

  resources :questions do
    resources :answers
  end

  resources :bounties
  get 'home/about'

  get 'home/contact'

  get 'home/index'

  root "home#index"

  devise_for :users, :path_prefix => 'my'
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  # scope "/account" do
  #   resources :users
  # end

end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  name        :text
#  correct     :boolean          default(FALSE)
#  question_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_answers_on_question_id  (question_id)
#

class Answer < ApplicationRecord
  belongs_to :question
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  # GET /answers
  # GET /answers.json
  def index
    @answers = @question.answers.all
  end

  # GET /answers/1
  # GET /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = @question.answers.build
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers
  # POST /answers.json
  def create
    @answer = @question.answers.build(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to [@question,@answer], notice: 'Answer was successfully created.' }
        format.json { render :show, status: :created, location: @answer }
      else
        format.html { render :new }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1
  # PATCH/PUT /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to [@question,@answer], notice: 'Answer was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer }
      else
        format.html { render :edit }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1
  # DELETE /answers/1.json
  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to question_answers_url, notice: 'Answer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_question
      @question = Question.find(params[:question_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_answer
      @answer = Answer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:name, :correct, :question_id)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= simple_form_for([@question, @answer]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <% #= f.association :question %>

    <%= f.input :name %>
    <%= f.input :correct %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing Answer</h1>

<%= render 'form', question: @question, answer: @answer %>

<%= link_to 'Show',  question_answer_path(@question,@answer) %> |
<%= link_to 'Back',  question_answers_path(@question)  %>

app/views/answers/index.html.erb
<h1>Answers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Correct</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.name %></td>
        <td><%= answer.correct %></td>
        <td><%= answer.question.name %></td>
        <td><%= link_to 'Show', question_answer_path(@question, answer) %></td>
        <td><%= link_to 'Edit', edit_question_answer_path(@question,answer) %></td>
        <td><%= link_to 'Destroy', [@question, answer], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_question_answer_path %>

app/views/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form', question: @question, answer: @answer %>

<%= link_to 'Back', question_answers_path 	 %>

app/views/answers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @answer.name %>
</p>

<p>
  <strong>Correct:</strong>
  <%= @answer.correct %>
</p>

<p>
  <strong>Question:</strong>
  <%= @answer.question.name %>
</p>

<%= link_to 'Edit', edit_question_answer_path([@answer]) %> |
<%= link_to 'Back', question_answers_path %>