config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  resources :posts do
    resources :comments
  end

  resources :question_banks
  resources :question_categories

# Below are nested resources TODO fix them
  resources :question_sets

  resources :questions do
    resources :answers
  end

  resources :bounties
  get 'home/about'

  get 'home/contact'

  get 'home/index'

  root "home#index"

  devise_for :users, :path_prefix => 'my'
  resources :users, only: [:index, :show, :edit, :update, :destroy]
  # scope "/account" do
  #   resources :users
  # end

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#

class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, :dependent => :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show

    @comment = Comment.new( :post => @post )
    @comments = @post.comments
    
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body, as: :ckeditor, input_html: {ckeditor: {toolbar: 'Full'}} %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
  <div class="">
    <%= link_to 'New Post', new_post_path %>
  </div>

  <div class="col-md-6" style="margin: auto;">

    <h2>Posts</h2>

    <% @posts.each do |post| %>
    <div class="container" style="background-color: azure; margin-bottom: 10%; ">
      <h3 style="font-width: 200%"><%= post.title.html_safe %></h3>
      <p><%= post.body.html_safe %></p>
      <p><%= post.created_at  %>
        <span style="float: right;"><%= post.user.name%></span>
      </p>
      <p style="color: blue"><%= link_to 'Read more', post %></p>
    </div>
    <% end %>

  </div>



</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="container">
  <div class="container" style="background-color: azure; margin-bottom: 10%;" >
    <h5><%= @post.title.html_safe %></h5>
      <p><%= @post.body.html_safe %></p>
      <p>Updated: <%= time_ago_in_words(@post.created_at) %> ago <span style="float: right;">Author: <%= @post.user.name%></span></p>
  </div>
</div>

<div class="jumbotron">
  <%= simple_form_for([@post, @comment]) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :body %>
      <%= f.association :post %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
</div>
<div class="container">

  <h1>Comments</h1>

  <table>
    <thead>
      <tr>
        <th>Body</th>
        <th>Post</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.body %></td>
          <td><%= comment.post %></td>
          <td><%= link_to 'Show', post_comment_path(comment) %></td>
          <td><%= link_to 'Edit', edit_post_comment_path(@post, comment) %></td>
          <td><%= link_to 'Destroy',  post_comment_path(@post, comment) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>


<p>
  <%= link_to 'Edit', edit_post_path(@post) %>
  <br>
  <%= link_to 'Back', posts_path %>
</p>